# Generated by Django 5.1.7 on 2025-07-19 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='Uploaded interview video file.', upload_to='interview_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of video upload.')),
                ('transcript', models.TextField(blank=True, help_text='Full transcription of the interview.', null=True)),
                ('filler_words_data', models.JSONField(blank=True, help_text='JSON array of detected filler words with details.', null=True)),
                ('word_confidences_data', models.JSONField(blank=True, help_text='JSON array of all words with their confidence scores.', null=True)),
                ('overall_clarity_confidence', models.FloatField(blank=True, help_text='Overall confidence score of the transcription (0.0-1.0).', null=True)),
                ('sentiment_data', models.JSONField(blank=True, help_text='JSON object summarizing sentiment analysis (e.g., overall sentiment, breakdown).', null=True)),
                ('pose_data', models.JSONField(blank=True, help_text='JSON array of pose analysis results per sampled frame.', null=True)),
                ('entities_data', models.JSONField(blank=True, help_text='JSON array of named entities detected.', null=True)),
                ('chapters_data', models.JSONField(blank=True, help_text='JSON array of auto-generated chapters.', null=True)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Analyzed', 'Analyzed'), ('Failed', 'Failed')], default='Uploaded', help_text='Current status of the video analysis.', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Details if the analysis failed.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the video (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
            },
        ),
    ]
