# Generated by Django 5.1.7 on 2025-07-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='uploader_name',
            field=models.CharField(blank=True, help_text='Name or identifier provided by the uploader (string)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='sentiment_data',
            field=models.JSONField(blank=True, help_text='JSON object summarizing sentiment analysis.', null=True),
        ),
    ]
