# Generated by Django 5.1.7 on 2025-07-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_interviewsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='assemblyai_job_id_field',
            field=models.CharField(blank=True, help_text='ID of the AssemblyAI transcription job.', max_length=100, null=True, unique=True),
        ),
    ]
